/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peregarcias.mightymotion;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.awt.Color;
import peregarcias.mightymotion.dataaccess.DataAccess;
import peregarcias.mightymotion.dto.Usuario;

/**
 *
 * @author morda
 */
public class JPanelCrearUsuario extends javax.swing.JPanel {

        Main jFrameMain;
        
    public JPanelCrearUsuario(Main jFrameMain) {
        initComponents();
        setBackground(new Color(185,208,214));
        this.jFrameMain=jFrameMain;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        chkIsInstructor = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        btnAltaUsuario1 = new javax.swing.JButton();

        setLayout(null);

        lblNombre.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        add(lblNombre);
        lblNombre.setBounds(70, 170, 44, 12);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre);
        txtNombre.setBounds(70, 190, 360, 30);

        lblEmail.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblEmail.setText("E-mail:");
        add(lblEmail);
        lblEmail.setBounds(70, 240, 34, 12);
        add(txtEmail);
        txtEmail.setBounds(70, 260, 360, 30);

        lblPassword.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblPassword.setText("Contraseña:");
        add(lblPassword);
        lblPassword.setBounds(70, 300, 60, 12);

        chkIsInstructor.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        chkIsInstructor.setText("Soy Instructor");
        chkIsInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIsInstructorActionPerformed(evt);
            }
        });
        add(chkIsInstructor);
        chkIsInstructor.setBounds(70, 360, 98, 19);

        btnVolver.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 44, 58));
        btnVolver.setText("VOLVER");
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver);
        btnVolver.setBounds(300, 400, 89, 26);
        add(lblMensaje);
        lblMensaje.setBounds(70, 440, 370, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(70, 320, 360, 30);

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoMM.jpg"))); // NOI18N
        jLabelLogo1.setText("jLabel1");
        add(jLabelLogo1);
        jLabelLogo1.setBounds(190, 20, 124, 108);

        jLabelTitle.setFont(new java.awt.Font("Modern M", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 44, 58));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Mighty Motion");
        add(jLabelTitle);
        jLabelTitle.setBounds(170, 130, 171, 24);

        btnAltaUsuario1.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnAltaUsuario1.setForeground(new java.awt.Color(0, 44, 58));
        btnAltaUsuario1.setText("REGISTRARSE");
        btnAltaUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaUsuario1ActionPerformed(evt);
            }
        });
        add(btnAltaUsuario1);
        btnAltaUsuario1.setBounds(100, 400, 129, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkIsInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIsInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIsInstructorActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        jFrameMain.mostrarJpanelCrearUsuario();
        jFrameMain.mostrarMain();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAltaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaUsuario1ActionPerformed
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setNom(txtNombre.getText());
        nuevoUsuario.setEmail(txtEmail.getText());
        String passwordHash = BCrypt.withDefaults().hashToString(12, txtPassword.getPassword());
        nuevoUsuario.setPasswordHash(passwordHash);
        nuevoUsuario.setInstructor(chkIsInstructor.isSelected());

        DataAccess da = new DataAccess();
        int nuevoUsuarioId = da.registrarUsuario(nuevoUsuario);
        nuevoUsuarioId = da.getUltimoIdRegistrado();
        nuevoUsuario.setId(nuevoUsuarioId);

        lblMensaje.setText("Usuario registrado correctamente con el ID = " + nuevoUsuarioId);
    }//GEN-LAST:event_btnAltaUsuario1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaUsuario1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chkIsInstructor;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
