/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peregarcias.mightymotion;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.awt.Color;
import peregarcias.mightymotion.dataaccess.DataAccess;
import peregarcias.mightymotion.dto.Usuario;

/**
 *
 * @author morda
 */
public class JPanelCrearUsuario extends javax.swing.JPanel {

        Main jFrameMain;
        
    public JPanelCrearUsuario(Main jFrameMain) {
        initComponents();
        setBackground(new Color(185,208,214));
        this.jFrameMain=jFrameMain;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        chkIsInstructor = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        btnAltaUsuario1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(185, 208, 214));
        setMinimumSize(new java.awt.Dimension(900, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setLayout(new java.awt.GridBagLayout());

        lblNombre.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 98, 5, 0);
        add(lblNombre, gridBagConstraints);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(txtNombre, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblEmail.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 98, 5, 0);
        add(lblEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(txtEmail, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblPassword.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 98, 5, 0);
        add(lblPassword, gridBagConstraints);

        chkIsInstructor.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        chkIsInstructor.setText("Soy Instructor");
        chkIsInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIsInstructorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 98, 10, 0);
        add(chkIsInstructor, gridBagConstraints);

        btnVolver.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 44, 58));
        btnVolver.setText("VOLVER");
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 40;
        add(btnVolver, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 23;
        add(lblMensaje, gridBagConstraints);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(txtPassword, gridBagConstraints);

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoMM512.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(-300, 0, 0, 0);
        add(jLabelLogo1, gridBagConstraints);

        jLabelTitle.setFont(new java.awt.Font("Modern M", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 44, 58));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Mighty Motion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jLabelTitle, gridBagConstraints);

        btnAltaUsuario1.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnAltaUsuario1.setForeground(new java.awt.Color(0, 44, 58));
        btnAltaUsuario1.setText("REGISTRARSE");
        btnAltaUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaUsuario1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 10, 0);
        add(btnAltaUsuario1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkIsInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIsInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIsInstructorActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        jFrameMain.mostrarJpanelCrearUsuario();
        jFrameMain.mostrarMain();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAltaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaUsuario1ActionPerformed
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setNom(txtNombre.getText());
        nuevoUsuario.setEmail(txtEmail.getText());
        String passwordHash = BCrypt.withDefaults().hashToString(12, txtPassword.getPassword());
        nuevoUsuario.setPasswordHash(passwordHash);
        nuevoUsuario.setInstructor(chkIsInstructor.isSelected());

        DataAccess da = new DataAccess();
        int nuevoUsuarioId = da.registrarUsuario(nuevoUsuario);
        nuevoUsuarioId = da.getUltimoIdRegistrado();
        nuevoUsuario.setId(nuevoUsuarioId);

        lblMensaje.setText("Usuario registrado correctamente con el ID = " + nuevoUsuarioId);
    }//GEN-LAST:event_btnAltaUsuario1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaUsuario1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chkIsInstructor;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
