/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peregarcias.mightymotion;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.plaf.metal.MetalIconFactory;
import peregarcias.mightymotion.dataaccess.DataAccess;
import peregarcias.mightymotion.dto.Usuario;

/**
 *
 * @author morda
 */
public class JPanelPantallaPrincipal extends javax.swing.JPanel {
    
    DataAccess da = new DataAccess();
        
    public JPanelPantallaPrincipal(Main jFrameMain, Usuario usuario) {
        initComponents();
        setSize(500, 600);
        setBounds(0, 0, 490, 590);
        setBackground(new Color(185,208,214));
        if (usuario != null) {
            lblBienvenida.setText("Bienvenido " + usuario.getNom());
        } else {
            lblBienvenida.setText("Bienvenido usuario desconocido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        btnMostrarUsuarios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsuarios1 = new javax.swing.JList<>();
        lblWorkouts = new javax.swing.JLabel();

        setLayout(null);

        lblBienvenida.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 44, 58));
        add(lblBienvenida);
        lblBienvenida.setBounds(10, 50, 500, 21);

        jScrollPane1.setViewportView(jListUsuarios);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 190, 320);

        btnMostrarUsuarios.setFont(new java.awt.Font("Modern M", 0, 14)); // NOI18N
        btnMostrarUsuarios.setForeground(new java.awt.Color(0, 44, 58));
        btnMostrarUsuarios.setText("MOSTRAR USUARIOS");
        btnMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarUsuariosActionPerformed(evt);
            }
        });
        add(btnMostrarUsuarios);
        btnMostrarUsuarios.setBounds(30, 90, 190, 22);

        jScrollPane2.setViewportView(jListUsuarios1);

        add(jScrollPane2);
        jScrollPane2.setBounds(270, 130, 190, 320);

        lblWorkouts.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        lblWorkouts.setForeground(new java.awt.Color(0, 44, 58));
        lblWorkouts.setText("WORKOUTS");
        lblWorkouts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblWorkouts);
        lblWorkouts.setBounds(310, 90, 90, 19);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed
        try {
            ArrayList<Usuario> usuarios = da.getUsuarios();
            DefaultListModel<String> dfm = new DefaultListModel<>();
            for (Usuario u: usuarios) {
                dfm.addElement(u.toString());
            }
            jListUsuarios.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelPantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JList<String> jListUsuarios1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblWorkouts;
    // End of variables declaration//GEN-END:variables
}
