/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peregarcias.mightymotion;

import at.favre.lib.crypto.bcrypt.BCrypt;
import javax.swing.JOptionPane;
import peregarcias.mightymotion.dataaccess.DataAccess;
import peregarcias.mightymotion.dto.Usuario;

/**
 *
 * @author morda
 */
public class JPanelIniciarSesion extends javax.swing.JPanel {

    DataAccess da = new DataAccess();
    Main jFrameMain;
    
    public JPanelIniciarSesion(Main jFrameMain) {
        initComponents();
        this.jFrameMain = jFrameMain;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasena = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnVolver = new javax.swing.JButton();
        btnEntrar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(185, 208, 214));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Modern M", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 44, 58));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Mighty Motion");
        add(jLabelTitle);
        jLabelTitle.setBounds(160, 140, 171, 24);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoMM.jpg"))); // NOI18N
        jLabelLogo.setText("jLabel1");
        add(jLabelLogo);
        jLabelLogo.setBounds(180, 30, 124, 108);

        txtEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailLoginActionPerformed(evt);
            }
        });
        add(txtEmailLogin);
        txtEmailLogin.setBounds(118, 221, 248, 30);

        jLabelUsuario.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 44, 58));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Usuario");
        add(jLabelUsuario);
        jLabelUsuario.setBounds(130, 200, 38, 12);

        jLabelContrasena.setFont(new java.awt.Font("Modern M", 0, 12)); // NOI18N
        jLabelContrasena.setForeground(new java.awt.Color(0, 44, 58));
        jLabelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContrasena.setText("Contraseña");
        add(jLabelContrasena);
        jLabelContrasena.setBounds(130, 260, 57, 12);

        txtPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLoginActionPerformed(evt);
            }
        });
        add(txtPasswordLogin);
        txtPasswordLogin.setBounds(120, 280, 248, 30);

        btnVolver.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 44, 58));
        btnVolver.setText("VOLVER");
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver);
        btnVolver.setBounds(200, 420, 90, 26);

        btnEntrar1.setFont(new java.awt.Font("Modern M", 0, 18)); // NOI18N
        btnEntrar1.setForeground(new java.awt.Color(0, 44, 58));
        btnEntrar1.setText("ENTRAR");
        btnEntrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });
        add(btnEntrar1);
        btnEntrar1.setBounds(200, 350, 90, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailLoginActionPerformed

    private void txtPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLoginActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    jFrameMain.mostrarJpanelIniciarSesion();
    jFrameMain.mostrarMain();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        Usuario usuario = da.getUsuario(txtEmailLogin.getText());
        if (usuario != null) {
            char[] passwordToVerify = txtPasswordLogin.getPassword();
            String userPasswordHashInDatabase = usuario.getPasswordHash();
            var result = BCrypt.verifyer().verify(passwordToVerify, userPasswordHashInDatabase);
            if (result.verified) {
                jFrameMain.mostrarJpanelPantallaPrincipal(usuario);
            }
            else {
                JOptionPane.showMessageDialog(this, "El usuario o la contraseña no son válidos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error: Usuario no encontrado");
        }
    }//GEN-LAST:event_btnEntrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables
}
