/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peregarcias.mightymotion;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author morda
 */
public class SideBarMenu extends javax.swing.JPanel {
    
    private JPanel sidebarMenu = new JPanel();
    private boolean isSideBarVisible;
    private int sidebarWidth = 200;
    private Timer timer;
    private int animStep = 10;
    JLabel lblLogo = new JLabel();
    ImageIcon logo = new ImageIcon("src\\main\\resources\\images\\MMFullTrans.png");
    private JLabel lblHome = new JLabel("Home");
    private JLabel lblIniciarSesion = new JLabel("Inciar Sesión");
    private JLabel lblMarca = new JLabel("MIGHTY MOTION");

    /**
     * Creates new form SideBarMenu
     */
    public SideBarMenu() {
        this.isSideBarVisible = false;
        
        initComponents();
        sidebarMenu.setLayout(new MigLayout("wrap 1", "[grow]", "[]10[]10[]10[]"));
        sidebarMenu.setSize(new Dimension(0,600));
        sidebarMenu.setVisible(false);
        
        sidebarMenu.add(lblLogo, "align center, grow");
        sidebarMenu.add(lblMarca, "align center, grow");
        lblMarca.setFont(new Font("Modern M", Font.BOLD, 20));
        lblLogo.setIcon(Inicio.redimensionarImagen(logo, 50, 50));
        sidebarMenu.add(lblHome, "grow");
        lblHome.setFont(new Font("Carlito", Font.PLAIN, 14));
        sidebarMenu.add(lblIniciarSesion, "grow");
        lblIniciarSesion.setFont(new Font("Carlito", Font.PLAIN, 14));
        
        this.setLayout(new BorderLayout());
        this.add(sidebarMenu, BorderLayout.WEST);
        
        timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                animateSidebar();
            }
        });
    }
    public void toggleSidebar() {
        isSideBarVisible = !isSideBarVisible;
        sidebarMenu.setVisible(true);
        timer.start();
    }
    public boolean isSideBarVisible() {
        return isSideBarVisible;
    }
    private void animateSidebar() {
        int currentWidth = sidebarMenu.getPreferredSize().width;
        if (isSideBarVisible) {
            if (currentWidth < sidebarWidth) {
                sidebarMenu.setPreferredSize(new Dimension(currentWidth + animStep, 600));
            } else {
                sidebarMenu.setPreferredSize(new Dimension(sidebarWidth, 600));
                timer.stop();
            }
        } else {
            if (currentWidth > 0) {
                sidebarMenu.setPreferredSize(new Dimension(currentWidth - animStep, 600));
            } else {
                sidebarMenu.setPreferredSize(new Dimension(0, 600));
                timer.stop();
                sidebarMenu.setVisible(false);
            }
        }
        sidebarMenu.revalidate();
        sidebarMenu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
